/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ksql;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class toppages extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5563878936831046088L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"toppages\",\"namespace\":\"ksql\",\"fields\":[{\"name\":\"gender\",\"type\":\"string\"},{\"name\":\"pageid\",\"type\":\"string\"},{\"name\":\"distinctusers\",\"type\":\"long\"},{\"name\":\"viewtime\",\"type\":\"long\"}],\"connect.name\":\"ksql.toppages\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<toppages> ENCODER =
      new BinaryMessageEncoder<toppages>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<toppages> DECODER =
      new BinaryMessageDecoder<toppages>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<toppages> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<toppages> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<toppages> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<toppages>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this toppages to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a toppages from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a toppages instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static toppages fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence gender;
  @Deprecated public java.lang.CharSequence pageid;
  @Deprecated public long distinctusers;
  @Deprecated public long viewtime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public toppages() {}

  /**
   * All-args constructor.
   * @param gender The new value for gender
   * @param pageid The new value for pageid
   * @param distinctusers The new value for distinctusers
   * @param viewtime The new value for viewtime
   */
  public toppages(java.lang.CharSequence gender, java.lang.CharSequence pageid, java.lang.Long distinctusers, java.lang.Long viewtime) {
    this.gender = gender;
    this.pageid = pageid;
    this.distinctusers = distinctusers;
    this.viewtime = viewtime;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gender;
    case 1: return pageid;
    case 2: return distinctusers;
    case 3: return viewtime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gender = (java.lang.CharSequence)value$; break;
    case 1: pageid = (java.lang.CharSequence)value$; break;
    case 2: distinctusers = (java.lang.Long)value$; break;
    case 3: viewtime = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'gender' field.
   * @return The value of the 'gender' field.
   */
  public java.lang.CharSequence getGender() {
    return gender;
  }


  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(java.lang.CharSequence value) {
    this.gender = value;
  }

  /**
   * Gets the value of the 'pageid' field.
   * @return The value of the 'pageid' field.
   */
  public java.lang.CharSequence getPageid() {
    return pageid;
  }


  /**
   * Sets the value of the 'pageid' field.
   * @param value the value to set.
   */
  public void setPageid(java.lang.CharSequence value) {
    this.pageid = value;
  }

  /**
   * Gets the value of the 'distinctusers' field.
   * @return The value of the 'distinctusers' field.
   */
  public long getDistinctusers() {
    return distinctusers;
  }


  /**
   * Sets the value of the 'distinctusers' field.
   * @param value the value to set.
   */
  public void setDistinctusers(long value) {
    this.distinctusers = value;
  }

  /**
   * Gets the value of the 'viewtime' field.
   * @return The value of the 'viewtime' field.
   */
  public long getViewtime() {
    return viewtime;
  }


  /**
   * Sets the value of the 'viewtime' field.
   * @param value the value to set.
   */
  public void setViewtime(long value) {
    this.viewtime = value;
  }

  /**
   * Creates a new toppages RecordBuilder.
   * @return A new toppages RecordBuilder
   */
  public static ksql.toppages.Builder newBuilder() {
    return new ksql.toppages.Builder();
  }

  /**
   * Creates a new toppages RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new toppages RecordBuilder
   */
  public static ksql.toppages.Builder newBuilder(ksql.toppages.Builder other) {
    if (other == null) {
      return new ksql.toppages.Builder();
    } else {
      return new ksql.toppages.Builder(other);
    }
  }

  /**
   * Creates a new toppages RecordBuilder by copying an existing toppages instance.
   * @param other The existing instance to copy.
   * @return A new toppages RecordBuilder
   */
  public static ksql.toppages.Builder newBuilder(ksql.toppages other) {
    if (other == null) {
      return new ksql.toppages.Builder();
    } else {
      return new ksql.toppages.Builder(other);
    }
  }

  /**
   * RecordBuilder for toppages instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<toppages>
    implements org.apache.avro.data.RecordBuilder<toppages> {

    private java.lang.CharSequence gender;
    private java.lang.CharSequence pageid;
    private long distinctusers;
    private long viewtime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ksql.toppages.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gender)) {
        this.gender = data().deepCopy(fields()[0].schema(), other.gender);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.pageid)) {
        this.pageid = data().deepCopy(fields()[1].schema(), other.pageid);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.distinctusers)) {
        this.distinctusers = data().deepCopy(fields()[2].schema(), other.distinctusers);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.viewtime)) {
        this.viewtime = data().deepCopy(fields()[3].schema(), other.viewtime);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing toppages instance
     * @param other The existing instance to copy.
     */
    private Builder(ksql.toppages other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.gender)) {
        this.gender = data().deepCopy(fields()[0].schema(), other.gender);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pageid)) {
        this.pageid = data().deepCopy(fields()[1].schema(), other.pageid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.distinctusers)) {
        this.distinctusers = data().deepCopy(fields()[2].schema(), other.distinctusers);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.viewtime)) {
        this.viewtime = data().deepCopy(fields()[3].schema(), other.viewtime);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'gender' field.
      * @return The value.
      */
    public java.lang.CharSequence getGender() {
      return gender;
    }


    /**
      * Sets the value of the 'gender' field.
      * @param value The value of 'gender'.
      * @return This builder.
      */
    public ksql.toppages.Builder setGender(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.gender = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gender' field has been set.
      * @return True if the 'gender' field has been set, false otherwise.
      */
    public boolean hasGender() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'gender' field.
      * @return This builder.
      */
    public ksql.toppages.Builder clearGender() {
      gender = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'pageid' field.
      * @return The value.
      */
    public java.lang.CharSequence getPageid() {
      return pageid;
    }


    /**
      * Sets the value of the 'pageid' field.
      * @param value The value of 'pageid'.
      * @return This builder.
      */
    public ksql.toppages.Builder setPageid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.pageid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'pageid' field has been set.
      * @return True if the 'pageid' field has been set, false otherwise.
      */
    public boolean hasPageid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'pageid' field.
      * @return This builder.
      */
    public ksql.toppages.Builder clearPageid() {
      pageid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'distinctusers' field.
      * @return The value.
      */
    public long getDistinctusers() {
      return distinctusers;
    }


    /**
      * Sets the value of the 'distinctusers' field.
      * @param value The value of 'distinctusers'.
      * @return This builder.
      */
    public ksql.toppages.Builder setDistinctusers(long value) {
      validate(fields()[2], value);
      this.distinctusers = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'distinctusers' field has been set.
      * @return True if the 'distinctusers' field has been set, false otherwise.
      */
    public boolean hasDistinctusers() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'distinctusers' field.
      * @return This builder.
      */
    public ksql.toppages.Builder clearDistinctusers() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'viewtime' field.
      * @return The value.
      */
    public long getViewtime() {
      return viewtime;
    }


    /**
      * Sets the value of the 'viewtime' field.
      * @param value The value of 'viewtime'.
      * @return This builder.
      */
    public ksql.toppages.Builder setViewtime(long value) {
      validate(fields()[3], value);
      this.viewtime = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'viewtime' field has been set.
      * @return True if the 'viewtime' field has been set, false otherwise.
      */
    public boolean hasViewtime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'viewtime' field.
      * @return This builder.
      */
    public ksql.toppages.Builder clearViewtime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public toppages build() {
      try {
        toppages record = new toppages();
        record.gender = fieldSetFlags()[0] ? this.gender : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.pageid = fieldSetFlags()[1] ? this.pageid : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.distinctusers = fieldSetFlags()[2] ? this.distinctusers : (java.lang.Long) defaultValue(fields()[2]);
        record.viewtime = fieldSetFlags()[3] ? this.viewtime : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<toppages>
    WRITER$ = (org.apache.avro.io.DatumWriter<toppages>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<toppages>
    READER$ = (org.apache.avro.io.DatumReader<toppages>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.gender);

    out.writeString(this.pageid);

    out.writeLong(this.distinctusers);

    out.writeLong(this.viewtime);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);

      this.pageid = in.readString(this.pageid instanceof Utf8 ? (Utf8)this.pageid : null);

      this.distinctusers = in.readLong();

      this.viewtime = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);
          break;

        case 1:
          this.pageid = in.readString(this.pageid instanceof Utf8 ? (Utf8)this.pageid : null);
          break;

        case 2:
          this.distinctusers = in.readLong();
          break;

        case 3:
          this.viewtime = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










